#
# drop tables if necessary
#
DROP TABLE IF EXISTS Stats;
DROP TABLE IF EXISTS ActStats;
DROP TABLE IF EXISTS ActMailblock;
DROP TABLE IF EXISTS ActReview;
DROP TABLE IF EXISTS ActProfileAnnotation;
DROP TABLE IF EXISTS ActProfile;
DROP TABLE IF EXISTS ActAnnotation;
DROP TABLE IF EXISTS Act;
DROP TABLE IF EXISTS AccessRule;
DROP TABLE IF EXISTS AccessApp;

