#
# drop tables if necessary
#
DROP TABLE IF EXISTS UserExperienceProfileAnnotation;
DROP TABLE IF EXISTS UserExperienceProfile;
DROP TABLE IF EXISTS UserExperienceAnnotation;
DROP TABLE IF EXISTS UserExperience;
DROP TABLE IF EXISTS UserPublicationProfileAnnotation;
DROP TABLE IF EXISTS UserPublicationProfile;
DROP TABLE IF EXISTS UserPublicationAnnotation;
DROP TABLE IF EXISTS UserPublication;
DROP TABLE IF EXISTS UserOrganizationProfileAnnotation;
DROP TABLE IF EXISTS UserOrganizationProfile;
DROP TABLE IF EXISTS UserOrganizationAnnotation;
DROP TABLE IF EXISTS UserOrganization;
DROP TABLE IF EXISTS UserContactProfileAnnotation;
DROP TABLE IF EXISTS UserContactProfile;
DROP TABLE IF EXISTS UserContactAnnotation;
DROP TABLE IF EXISTS UserContact;
DROP TABLE IF EXISTS UserAddressProfileAnnotation;
DROP TABLE IF EXISTS UserAddressProfile;
DROP TABLE IF EXISTS UserAddressAnnotation;
DROP TABLE IF EXISTS UserAddress;
DROP TABLE IF EXISTS UserActivity;
DROP TABLE IF EXISTS UserInvitation;
DROP TABLE IF EXISTS UserRelationManual;
DROP TABLE IF EXISTS UserGroupInApp;
DROP TABLE IF EXISTS UserInGroup;
DROP TABLE IF EXISTS UserRelation;
DROP TABLE IF EXISTS UserGroup;
DROP TABLE IF EXISTS AccessGroup;
DROP TABLE IF EXISTS AccessApp;
DROP TABLE IF EXISTS UserData;
DROP TABLE IF EXISTS UserSettings;
DROP TABLE IF EXISTS UserProfileAnnotation;
DROP TABLE IF EXISTS UserProfile;
DROP TABLE IF EXISTS UserAnnotation;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS AccessRule;
